version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    
    groups:
      tailwind:
        patterns:
          - tailwind*
          - "@tailwind*"
          - postcss
      mantine:
        patterns:
          - "@mantine*"
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"

    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
