import type { Artist } from "./type";

export const ARTIST_MOCK_DATA: Artist[] = [
  {
    id: "1",
    adminLabel: "artist1",
    name: "artist1",
    iconUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    tags: ["watercolor painting", "oil painting"],
    authorized: true,
    creationStatus: "CONFIRMED",
  },
  {
    id: "2",
    adminLabel: "artist2",
    name: "artist2",
    iconUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    tags: ["watercolor painting", "oil painting"],
    authorized: true,
    creationStatus: "DRAFT",
  },
  {
    id: "3",
    adminLabel: "artist3",
    name: "artist3",
    iconUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
    tags: [],
    authorized: true,
    creationStatus: "CONFIRMED",
  },
  {
    id: "4",
    adminLabel: "artist4",
    name: "artist4",
    iconUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9",
    tags: ["sculpture", "installation"],
    authorized: false,
    creationStatus: "DRAFT",
  },
  {
    id: "5",
    adminLabel: "artist5",
    name: "artist5",
    iconUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80",
    tags: ["digital art", "animation"],
    authorized: true,
    creationStatus: "CONFIRMED",
  },
  {
    id: "6",
    adminLabel: "artist6",
    name: "artist6",
    iconUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6",
    tags: ["photography"],
    authorized: false,
    creationStatus: "DRAFT",
  },
  {
    id: "7",
    adminLabel: "artist7",
    name: "artist7",
    iconUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    tags: ["illustration", "manga"],
    authorized: true,
    creationStatus: "CONFIRMED",
  },
  {
    id: "8",
    adminLabel: "artist8",
    name: "artist8",
    iconUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    tags: ["conceptual art"],
    authorized: true,
    creationStatus: "DRAFT",
  },
  {
    id: "9",
    adminLabel: "artist9",
    name: "artist9",
    iconUrl: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce",
    tags: ["performance art", "video art"],
    authorized: false,
    creationStatus: "CONFIRMED",
  },
  {
    id: "10",
    adminLabel: "artist10",
    name: "artist10",
    iconUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    tags: ["traditional art", "calligraphy"],
    authorized: true,
    creationStatus: "DRAFT",
  },
  {
    id: "11",
    adminLabel: "artist11",
    name: "artist11",
    iconUrl: "https://images.unsplash.com/photo-1552058544-f2b08422138a",
    tags: ["street art", "graffiti"],
    authorized: true,
    creationStatus: "CONFIRMED",
  },
  {
    id: "12",
    adminLabel: "artist12",
    name: "artist12",
    iconUrl: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39",
    tags: ["textile art", "fashion design"],
    authorized: false,
    creationStatus: "DRAFT",
  },
  {
    id: "13",
    adminLabel: "artist13",
    name: "artist13",
    iconUrl: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c",
    tags: ["ceramics", "pottery"],
    authorized: true,
    creationStatus: "CONFIRMED",
  },
  {
    id: "14",
    adminLabel: "artist14",
    name: "artist14",
    iconUrl: "https://images.unsplash.com/photo-1554151228-14d9def656e4",
    tags: ["mixed media", "collage"],
    authorized: true,
    creationStatus: "DRAFT",
  },
  {
    id: "15",
    adminLabel: "artist15",
    name: "artist15",
    iconUrl: "https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c",
    tags: ["printmaking", "etching"],
    authorized: false,
    creationStatus: "CONFIRMED",
  },
  {
    id: "16",
    adminLabel: "artist16",
    name: "artist16",
    iconUrl: "https://images.unsplash.com/photo-1504593811423-6dd665756598",
    tags: ["glass art", "sculpture"],
    authorized: true,
    creationStatus: "DRAFT",
  },
  {
    id: "17",
    adminLabel: "artist17",
    name: "artist17",
    iconUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    tags: ["jewelry design", "metalwork"],
    authorized: false,
    creationStatus: "CONFIRMED",
  },
  {
    id: "18",
    adminLabel: "artist18",
    name: "artist18",
    iconUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
    tags: ["woodworking", "furniture design"],
    authorized: true,
    creationStatus: "DRAFT",
  },
  {
    id: "19",
    adminLabel: "artist19",
    name: "artist19",
    iconUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9",
    tags: ["3D printing", "digital sculpture"],
    authorized: true,
    creationStatus: "CONFIRMED",
  },
  {
    id: "20",
    adminLabel: "artist20",
    name: "artist20",
    iconUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6",
    tags: ["sound art", "interactive installation"],
    authorized: false,
    creationStatus: "DRAFT",
  },
];
